import Head from 'next/head';
import { GetServerSideProps } from 'next'
import styles from '../styles/Home.module.css';

interface Props {
    time: string;
}

export default function Home({time}: Props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Next js on Azure Static Web Apps
                </h1>

                <p>{time}</p>
            </main>
        </div>
    );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
    return {
        props: {
            time: new Date().toString()
        }
    }
  }